### ISSUE TITLE
训练效率好低啊，加卡的提升的并不明显

### ISSUE THREAD

**Issue by yayaQAQ** [AI-confused/easy_task#1]
之前使用两张卡训练，使用率大部分时间在50%，有时候会跳到100%
后面使用六张卡训练，使用率大部分时间在10%，有时候会跳到100%
<img width="589" alt="image" src="https://user-images.githubusercontent.com/20497531/218924911-b84f45d1-2bde-4a59-9800-dd2a92ff9ab2.png">

**Comment by AI-confused** [comment]
这个是不是和数据的分布差别较大有关😂单机多卡分布训练我是直接用torch的方法，应该和这个训练框架没关系。
我问了下chatGPT这个问题，以下是它的回复：
1数据预处理和加载：如果数据预处理和加载的速度不够快，GPU可能会被迫等待数据，导致GPU利用率不均匀。
2数据集大小：如果数据集很小，GPU可能无法充分利用其计算能力，导致GPU利用率不均匀。
3模型复杂度：如果模型过于复杂，GPU可能会在某些计算中耗费更多的时间，导致GPU利用率不均匀。
4学习率和批次大小：如果学习率设置得太高或批次大小设置得太小，可能会导致GPU计算过于频繁，导致GPU利用率不均匀。
5GPU内存限制：如果GPU内存不足，模型可能无法完全加载到GPU中，导致GPU利用率不均匀。
6硬件故障：如果GPU硬件存在故障，可能会导致GPU利用率不均匀。

PS：我这边训练多卡没出现过类似情况，利用率基本能跑满，我写的这个框架主要是方便训练各种深度学习任务，只需要对少数部件进行修改
